/** レッスン作成用の統一エクスポート（Next.js の page コンポーネントと同様の import 口）。 */
export { Lesson } from "./components/lesson";
export { Callout } from "./components/callout";
export { InfoPanel } from "./components/info-panel";
export { Dialog } from "./components/dialog";
export { CharacterIntro } from "./components/character-intro";
export { CodeBlock } from "./components/code-block";
export { Quiz, LessonQuiz, CourseTestQuiz } from "./components/quiz";
export { MultiQuiz, LessonMultiQuiz, CourseTestMultiQuiz } from "./components/multi-quiz";
export { CodeArrange } from "./components/code-arrange";
export { FlowArrange } from "./components/flow-arrange";
export { ScoreBoard } from "./components/score-board";
export { PageSubmitBar } from "./components/page-submit-bar";
export { Reveal } from "./components/reveal";
export { MermaidDiagram } from "./components/mermaid-diagram";
export { SapErdDiagram } from "./components/sap-erd-diagram";
export { ExpandableFullscreen } from "./components/expandable-fullscreen";
export { DiagramCollapsibleHelp } from "./components/diagram-collapsible-help";
export { SapErdDiagramHelp } from "./components/sap-erd-diagram-help";
export { Figure } from "./components/figure";
export { LessonMeta } from "./components/lesson-meta";
export { LessonLinkButton } from "./components/lesson-link-button";
export { HorizontalLine, horizontalLineClasses, horizontalLineBorderColor } from "./components/horizontal-line";
export { mountLesson } from "./mount-lesson";
export { lessonChrome } from "./lib/lesson-chrome.ts";
export type { LessonChrome, SlideDefinition } from "./lib/types";
